version: 0.0
os: linux	 
hooks:	
  BeforeInstall:	 
    - location: scripts/install
      timeout: 300	     
      runas: root	      
    - location: scripts/startandbuild
      timeout: 300	     
      runas: root    
