version: 0.2 

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Gradle
      - curl -sL https://services.gradle.org/distributions/gradle-7.3.3-bin.zip -o /tmp/gradle-7.3.3-bin.zip
      - unzip -q /tmp/gradle-7.3.3-bin.zip -d /usr/local
      - export PATH=$PATH:/usr/local/gradle-7.3.3/bin
      - echo Installed Gradle version $(gradle --version)   
  pre_build:
    commands:
      - echo Setting up AWS credentials
      - export AWS_ACCESS_KEY_ID=AKIA6OCNVXYF2HMJSC3Z
      - export AWS_SECRET_ACCESS_KEY=GXr8ckJtIabLoMOAmwG3ALRKmF/z0NLNKltUDcPh 
  build:
    commands:
      - echo Building the Gradle project
      - gradle clean build 

      
  artifacts:
  files:
    - build/libs/*.jar
