version: 0.2
phases:
  build: 
    commands:
      - echo 'build started'
      - gradle clean build
      - ls /codebuild/output/src868196871/src/github.com/Aparna-SJ/mygraddleapp/
artifacts:
  files:
    - hello_world-0.0.1-SNAPSHOT.jar
    
