version: 0.2 

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - aws s3 cp build/libs/*.jar s3://ak2-codebuild-artifacts/*.jar
    
