version: 0.2 

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo "Executing pre-build phase"
  build:
    commands:
      - echo "Executing build phase"
      - ./gradlew build
  post_build:
    commands:
      - echo "Executing post-build phase"
      - aws s3 cp build/libs/*.jar s3://ak2-codebuild-artifacts/*.jar
    
